name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  deployment:
  workflow_dispatch:

env:
  DB_DATABASE: enso
  DB_USERNAME: enso
  DB_PASSWORD: secret

jobs:
  yarn:
    runs-on: ubuntu-20.04
    env:
      NODE_OPTIONS: --max_old_space_size=3072
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - name: 'install & build'
        run: |
          sed -i 's/GOOGLE_ANALITICS_TOKEN/${{ secrets.GOOGLE_ANALITICS_TOKEN }}/g' resources/views/stubs/production-index.blade.stub
          cp .env.example .env
          yarn install
          yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: resources
          path: |
            public/css/
            public/js/
            public/images/
            resources/views
  deploy:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'deployment' || github.event_name == 'push' }}
    needs: [yarn]
    steps:
      - uses: actions/checkout@v2
      - name: 'Trig envoyer'
        run: |
          curl ${{ secrets.DEPLOY_WEBHOOK }}
